// <auto-generated />
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241207122405_datatypechangeandseedingdata")]
    partial class datatypechangeandseedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeAge")
                        .HasColumnType("int");

                    b.Property<long>("EmployeePhone")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "developer with 3 years of experience",
                            Designation = "Developer",
                            EmployeeAge = 24,
                            EmployeePhone = 7894561230L,
                            Name = "Prakash"
                        },
                        new
                        {
                            Id = 2,
                            Description = "tester with 1 year of experience",
                            Designation = "Tester",
                            EmployeeAge = 22,
                            EmployeePhone = 123654789L,
                            Name = "Ganesh"
                        },
                        new
                        {
                            Id = 3,
                            Description = "DA with 1 year of experience",
                            Designation = "DA",
                            EmployeeAge = 25,
                            EmployeePhone = 123654259L,
                            Name = "Om"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
